[package]
name = "alfath_torrent"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "=0.4.28"
minijinja = "2.12.0"
once_cell = "1.21.3"
simplelog = "0.12.2"
time = "0.3.44"
tiny_http = "0.12.0"
tokio = { version = "*", features = ["full"] }
transmission-rpc = "0.5.0"
urlencoding = "2.1.3"
